# -*- coding: utf-8 -*-
import os
import re

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover - optional dependency
    def load_dotenv(*args, **kwargs):
        return False


load_dotenv()


DEFAULT_DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
_DASHSCOPE_NATIVE_SDK_URL_RE = re.compile(
    r"/api/v\d+(?:/(?:services|chat/completions|embeddings))?/?$",
    re.IGNORECASE,
)


def env_bool(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def normalize_dashscope_base_url(base_url: str | None) -> str:
    value = (base_url or DEFAULT_DASHSCOPE_BASE_URL).strip()
    if not value:
        return DEFAULT_DASHSCOPE_BASE_URL
    value = value.rstrip("/")
    return _DASHSCOPE_NATIVE_SDK_URL_RE.sub("/compatible-mode/v1", value)


DECAY_RATE = float(os.getenv("DECAY_RATE", "1e-8"))
EPISODE_TTL = int(os.getenv("EPISODE_TTL", "3600"))
PRUNE_C_VALID_THRESHOLD = int(os.getenv("PRUNE_C_VALID_THRESHOLD", "100"))
PRUNE_EVIDENCE_TOP_K = int(os.getenv("PRUNE_EVIDENCE_TOP_K", "5"))
DEFAULT_USER_ID = os.getenv("DEFAULT_USER_ID", "default_user")

DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY", "")
DASHSCOPE_BASE_URL = normalize_dashscope_base_url(
    os.getenv("DASHSCOPE_BASE_URL", DEFAULT_DASHSCOPE_BASE_URL)
)
GENERATION_API_KEY = os.getenv("GENERATION_API_KEY", DASHSCOPE_API_KEY)
GENERATION_BASE_URL = normalize_dashscope_base_url(
    os.getenv("GENERATION_BASE_URL", DASHSCOPE_BASE_URL)
)
EMBEDDING_API_KEY = os.getenv("EMBEDDING_API_KEY", DASHSCOPE_API_KEY)
EMBEDDING_BASE_URL = normalize_dashscope_base_url(
    os.getenv("EMBEDDING_BASE_URL", DASHSCOPE_BASE_URL)
)
GENERATION_MODEL = os.getenv("GENERATION_MODEL", "qwen3-1.7b")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-v2")
EMBEDDING_DIM = int(os.getenv("EMBEDDING_DIM", "1024"))
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "25"))
ENABLE_THINKING = env_bool("ENABLE_THINKING", False)

TEST_DATA_PATH = os.getenv("TEST_DATA_PATH", "./example.json")
TEST_DATASET_KEY = os.getenv("TEST_DATASET_KEY", "input_records_1_mock")
MAX_EPISODES = int(os.getenv("MAX_EPISODES", "6"))
DB_PATH = os.getenv("DB_PATH", "./DB/demo_db.kz")

ENABLE_DYNAMIC_EVOLUTION = env_bool("ENABLE_DYNAMIC_EVOLUTION", True)
ENABLE_EVENT_RELATIONS = env_bool("ENABLE_EVENT_RELATIONS", True)
LLM_CONCURRENCY = int(os.getenv("LLM_CONCURRENCY", "4"))
BULK_INGEST_MODE = env_bool("BULK_INGEST_MODE", False)
DEFERRED_EVOLUTION = env_bool("DEFERRED_EVOLUTION", False)
APPEND_FIRST_MODE = env_bool("APPEND_FIRST_MODE", True)

CONTEXT_REUSE_THRESHOLD = float(os.getenv("CONTEXT_REUSE_THRESHOLD", "0.50"))
CONTEXT_CONFLICT_THRESHOLD = float(os.getenv("CONTEXT_CONFLICT_THRESHOLD", "0.72"))
CONTEXT_CANDIDATE_LIMIT = int(os.getenv("CONTEXT_CANDIDATE_LIMIT", "24"))
CONTEXT_QUERY_CANDIDATE_LIMIT = int(os.getenv("CONTEXT_QUERY_CANDIDATE_LIMIT", "16"))
CONTEXT_EXTRACTION_BATCH_SIZE = int(os.getenv("CONTEXT_EXTRACTION_BATCH_SIZE", "8"))
CONTEXT_AWARE_EXTRACTION_LIMIT = int(os.getenv("CONTEXT_AWARE_EXTRACTION_LIMIT", "36"))
CONTEXT_REUSE_GATING_ENABLED = env_bool("CONTEXT_REUSE_GATING_ENABLED", True)
CONTEXT_REUSE_CANDIDATE_LIMIT = int(os.getenv("CONTEXT_REUSE_CANDIDATE_LIMIT", "8"))
CONTEXT_REUSE_SCORE_THRESHOLD = float(os.getenv("CONTEXT_REUSE_SCORE_THRESHOLD", "0.72"))
CONTEXT_REUSE_MIN_SUMMARY_OVERLAP = float(os.getenv("CONTEXT_REUSE_MIN_SUMMARY_OVERLAP", "0.65"))
CONTEXT_REUSE_MIN_EVIDENCE_OVERLAP = float(os.getenv("CONTEXT_REUSE_MIN_EVIDENCE_OVERLAP", "0.40"))
CONTEXT_REUSE_REQUIRE_EVIDENCE = env_bool("CONTEXT_REUSE_REQUIRE_EVIDENCE", True)
CONTEXT_REUSE_ALLOW_CROSS_SUBTYPE = env_bool("CONTEXT_REUSE_ALLOW_CROSS_SUBTYPE", False)
CONTEXT_REUSE_WEIGHT_SUMMARY = float(os.getenv("CONTEXT_REUSE_WEIGHT_SUMMARY", "0.45"))
CONTEXT_REUSE_WEIGHT_EVIDENCE = float(os.getenv("CONTEXT_REUSE_WEIGHT_EVIDENCE", "0.25"))
CONTEXT_REUSE_WEIGHT_ENTITY = float(os.getenv("CONTEXT_REUSE_WEIGHT_ENTITY", "0.15"))
CONTEXT_REUSE_WEIGHT_TEMPORAL = float(os.getenv("CONTEXT_REUSE_WEIGHT_TEMPORAL", "0.10"))
CONTEXT_REUSE_WEIGHT_SUBTYPE = float(os.getenv("CONTEXT_REUSE_WEIGHT_SUBTYPE", "0.05"))

REINFORCEMENT_STEP = float(os.getenv("REINFORCEMENT_STEP", "0.06"))
DECAY_STEP = float(os.getenv("DECAY_STEP", "0.04"))
STALE_SECONDS = int(os.getenv("STALE_SECONDS", "2592000"))
ARCHIVE_EVENT_SECONDS = int(os.getenv("ARCHIVE_EVENT_SECONDS", "7776000"))

RETRIEVAL_WEIGHT_EVENT_SIM = float(os.getenv("RETRIEVAL_WEIGHT_EVENT_SIM", "0.45"))
RETRIEVAL_WEIGHT_CONTEXT = float(os.getenv("RETRIEVAL_WEIGHT_CONTEXT", "0.15"))
RETRIEVAL_WEIGHT_RECENCY = float(os.getenv("RETRIEVAL_WEIGHT_RECENCY", "0.20"))
RETRIEVAL_WEIGHT_VALIDITY = float(os.getenv("RETRIEVAL_WEIGHT_VALIDITY", "0.10"))
RETRIEVAL_WEIGHT_SUPPORT = float(os.getenv("RETRIEVAL_WEIGHT_SUPPORT", "0.10"))
RETRIEVAL_DEFAULT_CANDIDATE_LIMIT = int(
    os.getenv("RETRIEVAL_DEFAULT_CANDIDATE_LIMIT", "40")
)

ENABLE_AUTO_CONSOLIDATION = env_bool("ENABLE_AUTO_CONSOLIDATION", True)
CONSOLIDATION_MIN_INTERVAL_SECONDS = int(
    os.getenv("CONSOLIDATION_MIN_INTERVAL_SECONDS", "1800")
)
WEAK_EDGE_PRUNE_THRESHOLD = float(os.getenv("WEAK_EDGE_PRUNE_THRESHOLD", "0.18"))
CONSOLIDATION_LOG_PATH = os.getenv(
    "CONSOLIDATION_LOG_PATH", "./outputs/consolidation_log.jsonl"
)
EVENT_CONSOLIDATION_WINDOW_SECONDS = int(
    os.getenv("EVENT_CONSOLIDATION_WINDOW_SECONDS", "172800")
)
EVENT_CONSOLIDATION_CANDIDATE_LIMIT = int(
    os.getenv("EVENT_CONSOLIDATION_CANDIDATE_LIMIT", "12")
)
EVENT_CONSOLIDATION_EMBEDDING_CANDIDATE_THRESHOLD = float(
    os.getenv("EVENT_CONSOLIDATION_EMBEDDING_CANDIDATE_THRESHOLD", "0.80")
)
EVENT_CONSOLIDATION_EMBEDDING_TOP_K = int(
    os.getenv("EVENT_CONSOLIDATION_EMBEDDING_TOP_K", "8")
)
EVENT_CONSOLIDATION_THRESHOLD = float(
    os.getenv("EVENT_CONSOLIDATION_THRESHOLD", "0.78")
)
EVENT_MERGE_TRACE_STRATEGY_VERSION = os.getenv(
    "EVENT_MERGE_TRACE_STRATEGY_VERSION", "v1"
)
EVENT_MERGE_TRACE_LOG_PATH = os.getenv(
    "EVENT_MERGE_TRACE_LOG_PATH", "./outputs/event_merge_trace.jsonl"
)

# ---------------- Registered Entity resolution ----------------
# 注册（重要）实体解析算法所需的阈值与预算控制。
REG_ENTITY_VECTOR_HIGH = float(os.getenv("REG_ENTITY_VECTOR_HIGH", "0.82"))
REG_ENTITY_VECTOR_LOW = float(os.getenv("REG_ENTITY_VECTOR_LOW", "0.55"))
REG_ENTITY_AMBIGUOUS_MARGIN = float(os.getenv("REG_ENTITY_AMBIGUOUS_MARGIN", "0.03"))
REG_ENTITY_LLM_BUDGET_PER_INGEST = int(
    os.getenv("REG_ENTITY_LLM_BUDGET_PER_INGEST", "8")
)
REG_ENTITY_STRATEGY_VERSION = os.getenv("REG_ENTITY_STRATEGY_VERSION", "v1")
REG_ENTITY_EVENT_SUMMARY_MAX = int(os.getenv("REG_ENTITY_EVENT_SUMMARY_MAX", "240"))

RECALL_MAX_CANDIDATES = int(os.getenv("RECALL_MAX_CANDIDATES", "10"))
RECALL_MIN_AGGREGATE_SCORE = float(os.getenv("RECALL_MIN_AGGREGATE_SCORE", "0.12"))
RECALL_TEMPORAL_WINDOW = int(os.getenv("RECALL_TEMPORAL_WINDOW", "604800"))
RECALL_TEMPORAL_LIMIT = int(os.getenv("RECALL_TEMPORAL_LIMIT", "5"))
RECALL_ENTITY_LIMIT = int(os.getenv("RECALL_ENTITY_LIMIT", "8"))
RECALL_SEMANTIC_LIMIT = int(os.getenv("RECALL_SEMANTIC_LIMIT", "8"))
RECALL_SEMANTIC_THRESHOLD = float(os.getenv("RECALL_SEMANTIC_THRESHOLD", "0.78"))
RECALL_STATE_LIMIT = int(os.getenv("RECALL_STATE_LIMIT", "5"))
RECALL_REFERENCE_LIMIT = int(os.getenv("RECALL_REFERENCE_LIMIT", "5"))

RECALL_WEIGHT_TEMPORAL = float(os.getenv("RECALL_WEIGHT_TEMPORAL", "0.10"))
RECALL_WEIGHT_ENTITY = float(os.getenv("RECALL_WEIGHT_ENTITY", "0.30"))
RECALL_WEIGHT_SEMANTIC = float(os.getenv("RECALL_WEIGHT_SEMANTIC", "0.35"))
RECALL_WEIGHT_STATE = float(os.getenv("RECALL_WEIGHT_STATE", "0.15"))
RECALL_WEIGHT_REFERENCE = float(os.getenv("RECALL_WEIGHT_REFERENCE", "0.10"))

# Entity Pattern v2 召回参数（详见 src/limem/retrieval/pattern_recall.py）
PATTERN_RECALL_FULL_RETURN_MAX_CHARS = int(
    os.getenv("PATTERN_RECALL_FULL_RETURN_MAX_CHARS", "2000")
)
PATTERN_RECALL_DEFAULT_TOP_K_SECTIONS = int(
    os.getenv("PATTERN_RECALL_DEFAULT_TOP_K_SECTIONS", "3")
)

RELATION_CLASSIFICATION_BATCH_SIZE = int(
    os.getenv("RELATION_CLASSIFICATION_BATCH_SIZE", "15")
)
RELATION_MIN_CONFIDENCE = float(os.getenv("RELATION_MIN_CONFIDENCE", "0.75"))
RELATION_MAX_LINKS_PER_EVENT = int(os.getenv("RELATION_MAX_LINKS_PER_EVENT", "3"))
ENABLE_DERIVE_OPERATION = env_bool("ENABLE_DERIVE_OPERATION", False)
MAX_DERIVATIONS_PER_BATCH = int(os.getenv("MAX_DERIVATIONS_PER_BATCH", "3"))

EXPORT_GRAPH = env_bool("EXPORT_GRAPH", True)
EXPORT_EVERY_EPISODE = env_bool("EXPORT_EVERY_EPISODE", True)
EXPORT_FULL_GRAPH = env_bool("EXPORT_FULL_GRAPH", True)
INCLUDE_EPISODES_IN_GRAPH = env_bool("INCLUDE_EPISODES_IN_GRAPH", False)
GRAPH_OUTPUT_DIR = os.getenv("GRAPH_OUTPUT_DIR", "./outputs")
GRAPH_MAX_EVENTS = int(os.getenv("GRAPH_MAX_EVENTS", "0"))
KUZU_EXPLORER_URL = os.getenv("KUZU_EXPLORER_URL", "")
